import type { AuditResult } from "@/lib/types";

function escapeCell(value: string): string {
  return value.replaceAll("|", "\\|").replaceAll("\n", " ");
}

export function createEvidenceReport(audit: AuditResult): string {
  const requirements = audit.requirements.map((item) =>
    `| ${escapeCell(item.id)} | ${item.severity} | ${item.status} | ${escapeCell(item.title)} | ${escapeCell(item.evidence.join("; ") || "No evidence found")} | ${escapeCell(item.nextAction)} |`,
  ).join("\n");
  const actions = audit.actionsPerformed.map((item) => `- **${item.label}** (${item.status}): ${item.detail}`).join("\n");
  const next = audit.nextActions.map((item, index) => `${index + 1}. ${item}`).join("\n");
  const operationalPriority = audit.operationalPriority
    ? `## Operational priority\n\n**${audit.operationalPriority.action}**\n\n${audit.operationalPriority.rationale}\n\nSelector: ${audit.operationalPriority.model ? `Gemma 4 (${audit.operationalPriority.model})` : "deterministic fallback"}\n\n`
    : "";

  return `# ${audit.projectName} — ProofFlow evidence pack

Generated: ${audit.completedAt}

Model: ${audit.model}

Readiness: **${audit.score}/100 — ${audit.overallStatus}**

Audit ID: \`${audit.id}\`

## Executive summary

${audit.executiveSummary}

## Autonomous actions performed

${actions}

## Requirement ledger

| ID | Severity | Status | Requirement | Evidence | Next action |
| --- | --- | --- | --- | --- | --- |
${requirements}

## Priority actions

${next}

${operationalPriority}## Source lock

- Rules: ${audit.sourceSnapshot.rules.url}
- Rules SHA-256: \`${audit.sourceSnapshot.rules.sha256}\`
- Repository: ${audit.sourceSnapshot.repository.url}
- Branch: \`${audit.sourceSnapshot.repository.defaultBranch}\`
- Deployment: ${audit.sourceSnapshot.deployment?.url ?? "not supplied"}

> Generated by ProofFlow Agent. Verify legal eligibility and final submission fields before filing.
`;
}
